spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamaker_database?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: s5T8f5zcaorcuiX6twPlidhdhyIipyxehYKncwffadajamTjC2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        